In [9]:
import json
import os
import pandas as pd
import numpy as np
from pathlib import Path
import collections
from sklearn.model_selection import train_test_split
from sklearn import metrics

import sys
sys.path.append("../")
from datatools.analyzer import *
from utterance.error_tools import *

from datatools.maneger import DataManager
from datatools.preproc import Preprocessor

In [10]:
data_path = "../X_y_data/context_content/"
data_name = "repeat.pickle"
dataM = DataManager(data_path)
_, y_repeat = dataM.load_data(data_name)

success load : ../X_y_data/context_content/repeat.pickle


In [11]:
data_path = "../X_y_data/context_content/"
data_name = "contradict.pickle"
dataM = DataManager(data_path)
_, y_contradict = dataM.load_data(data_name)

success load : ../X_y_data/context_content/contradict.pickle


In [12]:
path = "../eval_labeled/"

datalist = ['DCM', 'DIT', 'IRS']
convs = read_conv(path, datalist)

In [13]:
len(y_repeat)

1386

In [14]:
y = []
errors = ["Repetition", "Self-contradiction", "Contradiction"]
for conv in convs:
    # utt_list_conv = [""]*5
    utt_list_conv = []
    for i, ut in enumerate( conv ) :
        utt_list_conv.append(ut.utt)
        # システム発話で，[文脈-形式]のエラー
        if ut.is_system() and ut.is_exist_error():
            if ut.is_error_included(errors):
                y.append(1)
            else:
                y.append(0)

In [15]:
y_content = np.array(y_repeat) | np.array(y_contradict)

In [16]:
y_content

array([1, 0, 1, ..., 1, 1, 1])

In [17]:
score(y, y_content)

confusion matrix = 
 [[562 747]
 [ 18  59]]
accuracy =  0.44805194805194803
precision =  0.07320099255583126
recall =  0.7662337662337663
f1 score =  0.13363533408833522


In [18]:
y_repeat.count(1)

62

In [19]:
import sys
sys.path.append("../")
import numpy as np
from datatools.maneger import DataManager

data_path = "../X_y_data/y_pred/"
dataM = DataManager(data_path)
_, y_wrong = dataM.load_data("wrong.pickle")
_, y_cf = dataM.load_data("caseFrame.pickle")

success load : ../X_y_data/y_pred/wrong.pickle
success load : ../X_y_data/y_pred/caseFrame.pickle


In [20]:
y_content = np.array(y_wrong) | np.array(y_cf)

In [21]:
y = []
errors = ["Wrong information", "Semantic error"]
sys_utt = []
for conv in convs:
    utt_list_conv = []
    for i, ut in enumerate( conv ) :
        sys_utt.append(ut.utt)
        # システム発話で，[文脈-形式]のエラー
        if ut.is_system() and ut.is_exist_error():
            if ut.is_error_included(errors):
                y.append(1)
            else:
                y.append(0)

In [22]:
score(y, y_content)

confusion matrix = 
 [[655 328]
 [ 36 367]]
accuracy =  0.7373737373737373
precision =  0.5280575539568345
recall =  0.9106699751861043
f1 score =  0.6684881602914389


In [23]:
for p, y_ , utt in zip(y_wrong, y, sys_utt):
    if y_==0 and p==1:
        print(utt)

うれしいよね？
どきどき
九州のうまいものめぐりをしに旅行に行きたいと常日頃から思ってるんだよ。
暑い日はいつでも気をつけてください
夏休みは楽しいですね
こんにちは。ありがとう、水分とるように気を付けてます。
こんにちは。調子はどうですか？
北朝鮮が発射準備を進めるのです
健康のことを考えても、味のことを考えてもね。
許してくれてありがとうございます
ドライフラワーは手芸ですね
海は楽しいですね
潮風を感じられるのでしょうかね
外食は洋食がいいですね
はい。どこかへお出かけですか？
そうねんですね。ずっと南極や北極の氷が解けているからだと思っていました。
丁寧に心を込めた文章なら、うまくなくて通じると思うんだ。
確かにきちんとした場面でならつけないことの方が多いですね。
こんばんはー。気軽に声かけてね。
そういえば思い出したんですけど、遊園地にある大きな池は、防災も兼ねてるらしいですよ。
何か見るのですか？
池は寒いです
活発なのはいいことです。
活性が全体的に低いです
そういえば、家の近くでお祭りがありました。
対策は必要ないですか
強力なんだろうね
でしょ
そうはおっしゃらず笑
お大事に
大丈夫ですか。熱中症が出てますか？
おおいにありますね。
ご無理しないで下さいね。
ありがとうございます
うん
海まで散歩に行くのです
ぱたぱた
ありがとう
今は答えられないんです。
天気はいい感じよね
天気予報をする気象予報士の合格率は５％なんだって。
５％か。かなり難関だね。
太陽風や地場を予測する「宇宙天気予報」っていうのもあるんだって。
人類が初めて宇宙でプレイしたスポーツは、月面で行われたゴルフなんだよ。
ホント？月でゴルフってなんか不思議。
パーより３打少ないアルバトロスはホールインワンよりも出る確率が少ないんだって。
英語でコミュニケーションがとれるらしいです
英語は苦手ですか。コミュニケーションは難しいですね
コミュニケーションは得意です
時期から資格を取りますねぇ
何か資格を取るんですか？
こんにちは！海へ行きたいね。
おはおは
電池は必要なんですよねー
こんにちは
卓球は好きですよ。卓球よくされるんですか？
福原愛ちゃんですね？
暑い日には気をつけたいですね。
熱中症に気をつけないんですよねー
ところで好きな映画はなんですか？
行ったことないよ。イタリア料

In [24]:
utt_list_conv

[]