In [5]:
import json
import os
import pandas as pd
import numpy as np
from pathlib import Path
import collections
from sklearn.model_selection import train_test_split
from sklearn import metrics

import sys
sys.path.append("../")
from datatools.analyzer import *
from utterance.error_tools import *

from datatools.maneger import DataManager
from datatools.preproc import Preprocessor

In [2]:
data_path = "../X_y_data/context_content/"
data_name = "repeat.pickle"
dataM = DataManager(data_path)
_, y_repeat = dataM.load_data(data_name)

success load : ../X_y_data/context_content/repeat.pickle


In [3]:
data_path = "../X_y_data/context_content/"
data_name = "contradict.pickle"
dataM = DataManager(data_path)
_, y_contradict = dataM.load_data(data_name)

success load : ../X_y_data/context_content/contradict.pickle


In [6]:
path = "../eval_labeled/"

datalist = ['DCM', 'DIT', 'IRS']
convs = read_conv(path, datalist)

In [5]:
len(y_repeat)

1386

In [6]:
y = []
errors = ["Repetition", "Self-contradiction", "Contradiction"]
for conv in convs:
    # utt_list_conv = [""]*5
    utt_list_conv = []
    for i, ut in enumerate( conv ) :
        utt_list_conv.append(ut.utt)
        # システム発話で，[文脈-形式]のエラー
        if ut.is_system() and ut.is_exist_error():
            if ut.is_error_included(errors):
                y.append(1)
            else:
                y.append(0)

In [7]:
y_content = np.array(y_repeat) | np.array(y_contradict)

In [8]:
y_content

array([0, 0, 0, ..., 0, 0, 0])

In [9]:
score(y, y_content)

confusion matrix = 
 [[1145  164]
 [  27   50]]
accuracy =  0.8621933621933622
precision =  0.2336448598130841
recall =  0.6493506493506493
f1 score =  0.3436426116838488


In [10]:
y_repeat.count(1)

62

In [1]:
import sys
sys.path.append("../")

from datatools.maneger import DataManager

data_path = "../utterance/wrong/"
data_name = "wrong_tw_res.pickle"
dataM = DataManager(data_path)
_, y_wrong = dataM.load_data(data_name)

success load : ../utterance/wrong/wrong_tw_res.pickle


In [14]:
y = []
errors = ["Wrong information"]
sys_utt = []
for conv in convs:
    utt_list_conv = []
    for i, ut in enumerate( conv ) :
        sys_utt.append(ut.utt)
        # システム発話で，[文脈-形式]のエラー
        if ut.is_system() and ut.is_exist_error():
            if ut.is_error_included(errors):
                y.append(1)
            else:
                y.append(0)

In [12]:
score(y, y_wrong)

confusion matrix = 
 [[648 343]
 [ 15 380]]
accuracy =  0.7417027417027418
precision =  0.5255878284923928
recall =  0.9620253164556962
f1 score =  0.6797853309481217


In [16]:
for p, y_ , utt in zip(y_wrong, y, sys_utt):
    if y_==0 and p==1:
        print(utt)

こんにちは。はじめまして。
四国は行ったことありません。あなたは行かれたことありますか？
お遍路の逆回りは迷いやすくて大変なぶん、ご利益が大きいらしいよ。
元日に行くと、人の多さにびっくりしちゃうよね。
ラーメンもいいですね。お兄さんがいらっしゃるんですか？
何が好きなの？
好きですよ
のりが好きですね
のり美味しいね。私も好きだよ。
そうですね。
うれしいよね？
どきどき
人間関係を深めるためのあいさつとしてよく用いられるよね。
新しい会社での人間関係が難しくて嫌になっちゃうよ。
九州のうまいものめぐりをしに旅行に行きたいと常日頃から思ってるんだよ。
こんにちは！熱中症に気をつけて。
いつ
暑い日はいつでも気をつけてください
話は変わりますけど、アメリカの学校の夏休みは三ヶ月もあるって知ってました？
知りませんでした！長いですね
夏休みは楽しいですね
こんにちは。ありがとう、水分とるように気を付けてます。
行くのがいいですね
こんにちは。海へ行きたいね。
泳ぎが上手ですね
ありがとう。クロールが得意なんです。
クロールは得意ですね
そう、スイミングで習ってるんです。
こんにちは。調子はどうですか？
北朝鮮が発射準備を進めるのです
怖いですね。
最近は観ていません。
ビーチの場所取りが必要なんだよね。
ビーチに行きたいです？？
センスが良くないから、同じような服ばかり選んでしまうよ。
昨日は何を食べましたか？
美味しいね。エビの天ぷらが好きなんだ。
そういえば、あなたは美味しいものを食べるのが好きでしたよね？天ぷらは食べるのが好きですね
こんにちはーはじめましてー
桜ってとても綺麗ですよねぇ
沢山ありますね、何か美味しいものはありますか?
年をとっても学び続けるのが、長生きの秘訣なんだって。
こんにちはありです
よろしくお願いします
そうですね、あだ名はありますよ。
許してくれてありがとうございます
こんにちは。気軽に声かけてね。
力が必要ですか。
映画が楽しみです
天気がいいとそれだけで元気が出ちゃうよね。
朝から天気が暖かいですよねえ
一位ヶ岳は山口県の山ですね
こんにちは。気軽に声かけてね。
今どきデートのときに花を持っていく人っているのかな。
花には人にいい影響を与えてくれますね。
できたら、ドライフラワーの作り方を教えてほしいです。
ドライフラワーは手芸で

In [13]:
utt_list_conv

['こんにちは。好きな食べ物は何ですか？',
 'こんにちは、私はカレーが好きですね。あなたはどうですか？',
 '私も、占いは結構信じます。血液型から星座、六星のやつとか。',
 '結構当たりますよね。今までで一番良かった占い結果はどんなものでしたか？',
 '血液型占いとか、六星占術（細木数子の）とかです。',
 'なるほど。占い師に見てもらったことはあるのですか？',
 '特に、痛みがなければ行かなくても良いと思いますよ。',
 'そうなんですか。でもちょっと気になりますけどね。',
 'そうだよ。寒いし。結構つらい。',
 'もっと暖かいコートが欲しいところですね。',
 'もしかしたらその時チャットしてるかもしれないですね!',
 'ですね。その時どんなチャット内容だったか覚えています？',
 '１０年前に行方不明になった飛行機が突然現れて、乗っていた人たちにとっては、１０年経っていなくて・・・つまり、１０年後に来てしまったんです。',
 '不思議だ。それって時間を飛び越えたってことですか？',
 '「時は金なり」って昔の人は良く言ったものですね。',
 '確かにそうですよね。時間の使い方に気をつけてますか？',
 'ポーランドはどうでした？',
 'とても有意義に過ごせましたよ。そちらはいかがでしたか？',
 '私も実は。まだまだって感じですけどね・・!',
 'そうなんですか？まだまだ同士お互い頑張っていきましょう！',
 'はい、頑張ります。いつもはどんなことをしているんですか？仕事？学生？']