In [3]:
import json
import pandas as pd
import numpy as np
from pathlib import Path
import collections


from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [4]:
# path = "../error_category_classification/dbdc5_ja_dev_labeled/"
path = "../hand_labeled/"
datalist = ['DCM', 'DIT', 'IRS']

output = "./"

In [5]:
def read_json_with_NoErr(path:str, datalist:list) -> pd.DataFrame:
    cols = ['did', 'tid', 'usr', 'sys', 'ec']
    df = pd.DataFrame(index=[], columns=cols)

    for p in datalist:
        datapath = Path(path + p + '/')
        for file in datapath.glob("*.json"):
            with open(file, "r") as f:
                json_data = json.load(f)
                did = json_data["did"]
                for t in json_data["turns"]:
                    if t["turn-index"] == 0:
                        continue
                    if t["speaker"] == "U":
                        usr = t["utterance"]
                        continue
                    if t["speaker"] == "S" :
                        tid = t["turn-index"]
                        sys = t["utterance"]
                        if t["error_category"]:
                            ec = t["error_category"]
                        else:
                            ec = ["No-Err"]
                        df = df.append(pd.DataFrame([did, tid, usr, sys, ec], index = cols).T)
    df.reset_index(inplace=True, drop=True)
    return df

In [6]:
def extract_error(df, errors):
    utterances = []
    for d, u, s, e in zip(df.did, df.usr, df.sys, df.ec):
        for err in errors:
            if err in e:
                utterances.append([u, s])
    return utterances

In [7]:
def no_error(df):
    utterances = []
    system = []
    user = []
    for d, u, s, e in zip(df.did, df.usr, df.sys, df.ec):
        if e[0] == "No-Err":
            utterances.append([ u, s])
        # system.append(s)
        # user.append(u)
    return utterances

In [8]:
df = read_json_with_NoErr(path, datalist)

In [9]:
df

did tid                   usr  \
0     1470646494   2    そうですね。最近とても暑いですから。   
1     1470646494   4         休日に行きたいと思います。   
2     1470646494   6       はい。あなたは海に行きますか？   
3     1470646494   8                何故ですか？   
4     1470646494  10  そうですか。山に行くのはどうでしょうか？   
...          ...  ..                   ...   
1995  1503290726  12           何を別売りしているの？   
1996  1503290726  14            今は2回押してないよ   
1997  1503290726  16              ベーシックだよね   
1998  1503290726  18              君は女性なんだね   
1999  1503290726  20                 両性なのか   

                                           sys  \
0                                  海に行かないんですね？   
1                                     海は大丈夫ですね   
2                                       海は危険です   
3                                     海はいけないです   
4                                    わあ！いいですね！   
...                                        ...   
1995           地下鉄で。名大前ができてすごく便利になりましたね、ここの大学。   
1996  紅葉も遅いみたいですしね。私は、いつもベーッシクな色で変わりばえしないのですが。   
1997     何処にあるお店ですか？ベースコートもトップコートも塗ると持ちが違いますよ。   
1998                                    中間ですか？   
1999                          では、スポーツは何かしてますか？   

                                         ec  
0                           [Contradiction]  
1                     [Lack of information]  
2     [Ignore question, Self-contradiction]  
3                         [Ignore question]  
4                                  [No-Err]  
...                                     ...  
1995                           [Repetition]  
1996               [Topic transition error]  
1997               [Topic transition error]  
1998                  [Lack of information]  
1999               [Topic transition error]  

[2000 rows x 5 columns]

In [10]:
errors = ["Topic transition error", "Unclear intention", "Lack of information"]
errors = ["Lack of information"]
errors = ["Topic transition error"]

In [11]:
ut = extract_error(df, errors)

In [12]:
ut_no = no_error(df)

In [13]:
print(len(ut))
print(len(ut_no))
print(ut_no[0])

192
651
['そうですか。山に行くのはどうでしょうか？', 'わあ！いいですね！']


In [14]:
import spacy
nlp = spacy.load('ja_ginza')
vec_dim = nlp("形態素").vector.shape
vec_dim

(300,)

In [15]:
from pyknp import Juman
from sentence_transformers import SentenceTransformer
import scipy.spatial
model_path = "/home/yamada/Downloads/training_bert_japanese"
Nmodel = SentenceTransformer(model_path, show_progress_bar=False)
emb_dim = Nmodel.encode(["お辞儀をしている男性会社員"])[0].shape[0]

In [16]:
def _in(arg1, arg2):
    result = False
    if isinstance(arg1, list):
        for element in arg1:
            if isinstance(element, str):
                if element in arg2:
                    result = True
                    break
            else:
                if element == arg2:
                    result = True
                    break
    else:
        if isinstance(arg1, str):
            if arg1 in arg2:
                result = True
        else:
            if arg1 == arg2:
                result = True
    return result

In [17]:
def filter_pos_vector(pos_list, text):
    vec = np.zeros(vec_dim)
    doc = nlp(text, disable=['ner'])
    for token in doc:
        # print(token, token.tag_)
        if "助動詞" not in token.tag_ and _in(pos_list, token.tag_):
            # print(token, token.tag_)
            vec += token.vector
    return vec

In [18]:
def feature_extraction(pos_list, convs, mode, is_norm=False):
    feature_list = []
    for utt in convs:

        if mode == "dif":
            vector = Nmodel.encode(utt)
            # usr_vec = filter_pos_vector(pos_list, utt[0] )
            usr_vec = vector[0]
            # sys_vec = filter_pos_vector(pos_list, utt[1] )
            sys_vec = vector[1]
            dif_vec = usr_vec - sys_vec
            # if np.linalg.norm(dif_vec)==0:
            #     print(utt)
            if is_norm:
                # print(np.linalg.norm(dif_vec))
                if np.linalg.norm(dif_vec)==0:
                    vec = np.concatenate( [dif_vec, dif_vec/0.05] )
                else:
                    vec = np.concatenate( [dif_vec, dif_vec/np.linalg.norm(dif_vec)] )
                feature_list.append(vec)
            else:
                feature_list.append(dif_vec)
    
    return np.array(feature_list, dtype="float32")


In [19]:
def remove_norm_zero(pos_list, convs):
    convs_removed = []
    for utt in convs:
        usr_vec = filter_pos_vector(pos_list, utt[0] )
        sys_vec = filter_pos_vector(pos_list, utt[1] )
        dif_vec = usr_vec - sys_vec
        if np.linalg.norm(dif_vec)==0 or np.linalg.norm(usr_vec)==0 or np.linalg.norm(sys_vec)==0:
            continue
        convs_removed.append(utt)
    return convs_removed

In [20]:
pos_list = ["名詞", "動詞", "形状詞", "形容詞"]
ut_new = remove_norm_zero(pos_list, ut)
ut_no_new = remove_norm_zero(pos_list, ut_no)

In [21]:
import random
def fake_error(convs, times):
    user_list = []
    system_list = []
    for utt in convs:
        user_list.append(utt[0])
        system_list.append(utt[1])
    
    fake_convs = []
    for _ in range(times):
        fake_convs.append( [random.choice(user_list), random.choice(system_list)] )
    return fake_convs

In [22]:
fake_error(ut_no_new, len(ut_no_new)-len(ut_new))

[['私は洋楽が好きなんです', '女王の読みは、「じょうおう」ではなく「じょおう」が公式の読み方らしいよ。'],
 ['私は今も時々スキーに行きますよ。',
  '私の場合、カミングアウトバラエティ秘密のケンミンSHOWが好きなので、それをイメージして竹田城跡にとても興味を持ちました。'],
 ['割りと好きなものが多く、嫌いなものは少ないですよ。ただエビアレルギーなので困っていますが。', '音楽は好きですか？'],
 ['君は病気してないかい？', '正しいにほんの言葉を使うことが求められているよね。'],
 ['そうなんです。色んなものがトッピングされていてとてもかわいいし、見た目だけじゃなくておいしいです。',
  '何かペットを飼っていますか？飼っていましたか？'],
 ['そうだね。でも美味しいから食べちゃうよね。', 'ですなっ、おやすみんちですぅ\u3000\u3000\u3000'],
 ['お好きな食べ物は何ですか？',
  '4、5年前にユニバーサル・スタジオ・ジャパンに一度行った事があり、Ban汗ブロックロールオンに乗った事を覚えています。あとは大きなジョーズのオブジェの前で写真を撮りました。'],
 ['確かに気をつけて泳がないといけませんね',
  '東京ディズニーランドのカピターノ・ミッキー・トリプルルームでは、ロズにどのようなことを話しかけられるのでしょうか？ 。'],
 ['こんにちは、千原ジュニアですね。', 'いいえ、健康です。'],
 ['青い空が最高だね', '私が住んでいる横浜では、JTBを見かけません。'],
 ['チョコレートです。あなたの好きな食べ物はなんですか？', 'そば湯にそば粉を足してるのかな？'],
 ['他にはスポーツをしたことはありますか？',
  '最近は色々な動物がいるカフェがありますが、神戸にある8b DOLCEではインコ味のアイスクリームが売っているのをご存知ですか？ 。'],
 ['温泉に行きます。貴方は？', '湖は美しいですね'],
 ['暑いですよね、毎日ー', '科学の進歩は、目を見張るものがあるよね。'],
 ['あまりミスチルの曲を知らないんです。あなたは何が好きですか？', '晴れか雨かで、その日の気分が決まることがあるよね。'],
 ['私もそう思います', 'はい、でもまだ

In [23]:
UT = ut_new + fake_error(ut_no_new, len(ut_no_new)-len(ut_new))
UT_NO = ut_no_new


In [24]:
print("UT: {0}".format(len(UT)))
print("UT_NO: {0}".format(len(UT_NO)))

UT: 528
UT_NO: 528


In [25]:
X = feature_extraction(pos_list, UT + UT_NO , mode="dif", is_norm=True)
y = np.concatenate( [ np.ones(len(UT)), np.zeros(len(UT_NO)) -1 ] )
y

array([ 1.,  1.,  1., ..., -1., -1., -1.])

In [26]:
print("ut: {0}, ut_new: {1}, dif:{2}".format(len(ut), len(ut_new), len(ut)- len(ut_new)))
print("ut_no: {0}, ut_no_new: {1}, dif:{2}".format(len(ut_no), len(ut_no_new), len(ut_no)- len(ut_no_new)))

ut: 192, ut_new: 170, dif:22
ut_no: 651, ut_no_new: 528, dif:123


In [27]:
model = SVC(kernel="rbf", random_state=2, C=0.1)


In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [29]:
model.fit(X_train, y_train)

SVC(C=0.1, random_state=2)

In [30]:
y_pred = model.predict(X_test)
# y_pred = np.ones(len(y_test))-2

In [31]:
len(y_test)

212

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
print('confusion matrix = \n', confusion_matrix(y_true=y_test, y_pred=y_pred))
print('accuracy = ', accuracy_score(y_true=y_test, y_pred=y_pred))
print('precision = ', precision_score(y_true=y_test, y_pred=y_pred))
print('recall = ', recall_score(y_true=y_test, y_pred=y_pred))
print('f1 score = ', f1_score(y_true=y_test, y_pred=y_pred))

confusion matrix = 
 [[35 78]
 [ 2 97]]
accuracy =  0.6226415094339622
precision =  0.5542857142857143
recall =  0.9797979797979798
f1 score =  0.708029197080292


In [75]:
for x in ut_no[:10]:
    
    f = feature_extraction(pos_list, x, mode="dif", is_norm=True)
    pred = np.argmax( clf.predict(f), axis=0 )
    print(pred, x)

0 ['そうですか。山に行くのはどうでしょうか？', 'わあ！いいですね！']
0 ['明日はとても暑くなるみたいですね。', 'ご存知になりたいです']
0 ['涼しくなってきたら、一緒に山へ行きたいですね。', 'ご存知ですいますよねー']
0 ['美味しいですね。', '美味しいよ']
0 ['でも高いですね', 'いくら']
1 ['サスペンスが好きです', '映画はヒューマン系が好きですね']
0 ['そうですか', 'あはい']
0 ['こんばんは。今日は暑かったですね。', 'ところで、スイカの種って実は栄養豊富なんだそうですよ。']
0 ['ありがとう。野菜もたっぷり食べて、栄養をバランスよく摂りたいです。', '野菜でヘルシーよねー']
0 ['こんにちは。元気ですね', '夕食は食べましたか？']


In [67]:
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier()

In [68]:
clf.fit(X_train, y_train)

AdaBoostClassifier()

In [69]:
y_pred = clf.predict(X_test)
print('confusion matrix = \n', confusion_matrix(y_true=y_test, y_pred=y_pred))
print('accuracy = ', accuracy_score(y_true=y_test, y_pred=y_pred))
print('precision = ', precision_score(y_true=y_test, y_pred=y_pred))
print('recall = ', recall_score(y_true=y_test, y_pred=y_pred))
print('f1 score = ', f1_score(y_true=y_test, y_pred=y_pred))

confusion matrix = 
 [[161  64]
 [ 80 118]]
accuracy =  0.6595744680851063
precision =  0.6483516483516484
recall =  0.5959595959595959
f1 score =  0.6210526315789473


['test_sen.ipynb',
 '.gitignore',
 'LiveComp',
 'paper',
 'UNI',
 '.git',
 'theme',
 'corpus',
 'test_bert.py',
 'sentece.py',
 'path_test.py']