In [1]:
import re
import sys
import json


import sys
sys.dont_write_bytecode = True
sys.path.append('../')
from datatools.analyzer import *

from datatools.maneger import DataManager
from datatools.preproc import Preprocessor

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [2]:
from response.feature import Feature

In [3]:
F_path = "../X_y_data/response2/"
F_name = "Classify_F.pickle"
featureM = DataManager(F_path)
F = featureM.load_data(F_name)

success load : ../X_y_data/response2/Classify_F.pickle


In [4]:
model_path = "../models/response2/"
model_name = "Classify_M.pickle"
modelM = DataManager(model_path)
lr = modelM.load_data(model_name)

success load : ../models/response2/Classify_M.pickle


In [18]:
# path = "../../corpus/hand_labeled/"
path = "../../corpus/hand_labeled/"
datalist = ['DCM', 'DIT', 'IRS']
convs = read_conv(path, datalist)

In [6]:
usr_utt = []
y = []
for conv in convs:
    for i, ut in enumerate( conv ) :
        # if ut.is_system() and ut.is_exist_error():
        #     if conv[i-1].is_type_inclued("質問"):
        
        if not ut.is_system() :
            usr_utt.append(ut.utt)
            if ut.is_exist_type():
                y.append(1)
            else:
                y.append(0)


In [7]:
print("len of y:{0},  counts:{1}".format(len(y), y.count(1)))

len of y:2000,  counts:637


In [8]:
# 正解率を見ておく
from tqdm import tqdm
print(F.feature_num)
usr = []
for i, x_t_str in enumerate( tqdm(usr_utt) ):
    x = F.featurization(x_t_str)
    usr.append(x)
usr_ = np.array(usr)

  0%|          | 0/2000 [00:00<?, ?it/s]

20960


100%|██████████| 2000/2000 [07:48<00:00,  4.27it/s]


In [9]:
y_pred = lr.predict(usr_)

In [10]:
fixed_y = []
# {'YN': 0, 'WH': 1, 'please': 2, 'proposal': 3, 'plain': 4}
for p in y_pred:
    if p <= 3:
        fixed_y.append(1)
    else:
        fixed_y.append(0)

In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
print('confusion matrix = \n', confusion_matrix(y_true=y, y_pred=fixed_y))
print('accuracy = ', accuracy_score(y_true=y, y_pred=fixed_y))
print('precision = ', precision_score(y_true=y, y_pred=fixed_y))
print('recall = ', recall_score(y_true=y, y_pred=fixed_y))
print('f1 score = ', f1_score(y_true=y, y_pred=fixed_y))

confusion matrix = 
 [[1116  247]
 [  94  543]]
accuracy =  0.8295
precision =  0.6873417721518987
recall =  0.8524332810047096
f1 score =  0.7610371408549405


In [12]:
# チェック
# count = 0
# for utt, y_, fixed in zip(usr_utt, y, fixed_y):
#     if y_==0 and fixed==1:
#         print(utt)
#         count+=1
# print(count)

1000円ぐらいかな？
海いいですね
海外の海もいいものですよね
魚もおいしいですよね
船旅もいいらしいですね
台風は怖いですよね
こんにちは！暑いから海行きたいね！
いいお天気ですね
雨がやみました
鈴木選手はワールドカップで活躍しましたね
だよね〜
え〜欲しいの？わたしは要らないな
私は冷夏の方が嬉しいかな？
楽しい事をしていると時間を忘れますよね？
晴れた日にいきたいですよね
歩きにくいですものね
確かに気をつけて泳がないといけませんね
急な高波は危ないですね
一気に読みたいですよね
焦点は合うけど疲れたら頭がボーっとするね
椅子を工夫して腰が痛くならないようにしています
ストレッチをするとよいよ
前の日食べた物とかも影響するよね
姿勢に気をつけて丈夫なままでいたい
そうなの？すごいね。
おお！道路を横切るとは！　エゾシカはひかれちゃうんです
凍らせると糖度は上がるっていうよね
明日は晴れるといいですね
カキ氷は好き？
嬉しいですね
青い海と空、最高ですね！
天気がいいですね
太陽が出ていると暖かくていいですね
聞いたことがないですね
それは私の質問の答えではないですよ？
ああ。周りの女子の話か。そう？
健康が一番だよね。君は結婚してるのかい？
すごいですね！
扇風機も併用するのさ。塩分を補給するのも良いらしいよ？
行きたいね！ビーチバレーしたいな
砂浜がとても熱くてやけどしそう
青い空が最高だね
海水浴は楽しいですよね
夏の晴れた日の海は最高ですね
でも、たまに荒ぶりますよね
湖も楽しいですよ
泳いでるニジマスなんかがよく見えますもんね
勉強になりました
子供のころの女子はしっかりしている子が多いですね
キャンプで食べるお肉はおいしいよね
毎朝食べていますよ
バナナは栄養の吸収が良いから朝食べると良いらしいですよ
早く冬こないかなあ
友達と飲んでいました
飲み過ぎました
そんなことはないですよ
昔、猫を飼っていました
薄い芸ですか。どんな芸なんでしょうね
暇ですね
写真はいいですね
そうですか？
趣味はいいですね
美味しいですよね
元気になれるんですよね
塩をかけても美味しいですよ
どんな食べ物にも合いますね
海を見ると元気になれますよね
癒しがあります
夏場はそうですね
この短時間に何があったの！まあまあ、笑って笑って
そらそうよ
多いって今言うたやんけ


In [15]:
from tqdm import tqdm
def search_utt(convs, query):
    i=0
    for i, conv in enumerate( convs ):
        for ut  in conv:
            if query in ut.utt:
                print(i, ut.did, ut.utt)



In [16]:
search_utt(convs, "魚も")

4 1502868470 魚もおいしいですよね
165 1471414705 海水浴です。魚も見えましたよ
165 1471414705 海水浴です。魚も見えましたよ


In [17]:
len(convs)

200

In [ ]:
# ここから Sentence-BERT vs 後ろ向き

from sentence_transformers import SentenceTransformer
from sentence_transformers import models ,losses
from sentence_transformers.readers import InputExample
from sentence_transformers.losses import TripletDistanceMetric, SoftmaxLoss
from sentence_transformers.evaluation import TripletEvaluator
from sentence_transformers.readers import TripletReader
from sentence_transformers.datasets import SentencesDataset
from torch.utils.data import DataLoader

In [19]:
type_num = 0
neutral_num = 0
# 0: not error, 1: newtral, 2: error
X = []
for conv in convs:
    for i, ut in enumerate( conv ) :
        # if ut.is_system() and ut.is_exist_error():
        #     if conv[i-1].is_type_inclued("質問"):
        usr_utt.append(ut.utt)
        # ユーザ発話駆動
        if not ut.is_system():
            if ut.is_exist_type():
                type_num += 1
                # システムがエラー
                if conv[i+1].is_exist_error():
                    X.append( InputExample(texts=[ut.utt, conv[i+1].utt], label=2 ) )
                # エラーではない
                else:
                    X.append( InputExample(texts=[ut.utt, conv[i+1].utt], label=0 ) )
            # ニュートラル
            else :
                if neutral_num <= type_num:
                    if not conv[i+1].is_exist_error():
                        neutral_num += 1
                        X.append( InputExample(texts=[ut.utt, conv[i+1].utt], label=1 ) )


In [21]:
X_train, X_test = train_test_split(X, train_size=0.7, random_state=4)

In [22]:
from sentence_transformers import SentenceTransformer
from sentence_transformers import models

download_path = "../../corpus/"
# download_path = ""
transformer = models.Transformer(download_path+'cl-tohoku/bert-base-japanese-whole-word-masking')
pooling = models.Pooling(transformer.get_word_embedding_dimension(),    
  pooling_mode_mean_tokens=True,
  pooling_mode_cls_token=False, 
  pooling_mode_max_tokens=False
)
model = SentenceTransformer(modules=[transformer, pooling])

sentences = ['吾輩は猫である',  '本日は晴天なり']
embeddings = model.encode(sentences)

for i, embedding in enumerate(embeddings):
  print("[%d] : %s" % (i, embedding.shape, ))

Some weights of the model checkpoint at ../../corpus/cl-tohoku/bert-base-japanese-whole-word-masking were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


[0] : (768,)
[1] : (768,)


In [23]:
BATCH_SIZE = 32
NUM_EPOCHS = 3
EVAL_STEPS = 1000
WARMUP_STEPS = int(len(X_train) // BATCH_SIZE * 0.1) 
OUTPUT_PATH = "../../corpus/sbert_ignore"

In [24]:
train_data = SentencesDataset(X_train, model=model)
train_dataloader = DataLoader(train_data, shuffle=True,  batch_size=BATCH_SIZE)
train_loss = losses.SoftmaxLoss(model=model, sentence_embedding_dimension=model.get_sentence_embedding_dimension(), num_labels=3)

In [25]:
model.fit(train_objectives=[(train_dataloader, train_loss)],
         epochs=NUM_EPOCHS,
         evaluation_steps=EVAL_STEPS,
         warmup_steps=WARMUP_STEPS,
         output_path=OUTPUT_PATH
         )

Epoch:   0%|          | 0/3 [00:00<?, ?it/s]

Iteration:   0%|          | 0/20 [00:00<?, ?it/s]

Iteration:   0%|          | 0/20 [00:00<?, ?it/s]

Iteration:   0%|          | 0/20 [00:00<?, ?it/s]

In [19]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn import svm
# clf = AdaBoostClassifier()
clf = svm.SVC(kernel='rbf', gamma =0.0001, C=1000)

In [21]:
from sentence_transformers import SentenceTransformer
from sentence_transformers import models
bert_path = "../../corpus/sbert_ignore"
sbert = SentenceTransformer(bert_path)

In [22]:
def text2vec(text):
    sentences = []
    if isinstance(text, str):
        sentences = [text]
    elif isinstance(text, list):
        sentences = text
    
    return sbert.encode(sentences)

def text2feature(text):
    vector = text2vec(text)
    diff = np.abs( vector[0] - vector[1] )
    return np.concatenate([vector.flatten(), diff])

In [23]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn import svm
# clf = AdaBoostClassifier()
clf = svm.SVC(kernel='rbf', gamma =0.0001, C=1000)

In [24]:
type_num = 0
neutral_num = 0
# 0: not error, 1: newtral, 2: error
X = []
y = []
for conv in convs:
    for i, ut in enumerate( conv ) :
        # if ut.is_system() and ut.is_exist_error():
        #     if conv[i-1].is_type_inclued("質問"):
        usr_utt.append(ut.utt)
        # ユーザ発話駆動
        if not ut.is_system():
            if ut.is_exist_type():
                type_num += 1
                # システムがエラー
                if conv[i+1].is_exist_error():
                    # X.append( InputExample(texts=[ut.utt, conv[i+1].utt], label=2 ) )
                    # X.append( text2vec([ut.utt, conv[i+1].utt]).flatten()  )
                    X.append( [ut.utt, conv[i+1].utt] )
                    y.append(2)
                # エラーではない
                else:
                    # X.append( InputExample(texts=[ut.utt, conv[i+1].utt], label=0 ) )
                    # X.append( text2vec([ut.utt, conv[i+1].utt]).flatten() )
                    X.append( [ut.utt, conv[i+1].utt] )
                    y.append(0)
            # ニュートラル
            else :
                if neutral_num <= type_num:
                    if not conv[i+1].is_exist_error():
                        neutral_num += 1
                        # X.append( InputExample(texts=[ut.utt, conv[i+1].utt], label=1 ) )
                        # X.append( text2vec([ut.utt, conv[i+1].utt]).flatten()  )
                        X.append( [ut.utt, conv[i+1].utt] )
                        y.append(1)

In [25]:
X_train_str, X_test_str, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=5)

In [26]:
X_train = [ text2feature(x) for x in X_train_str]
X_test = [ text2feature(x) for x in X_test_str]

In [27]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn import svm
# clf = AdaBoostClassifier()
clf = svm.SVC(kernel='rbf', gamma =0.0001, C=1000)

In [28]:
clf.fit(X_train, y_train)

SVC(C=1000, gamma=0.0001)

In [29]:
y_pred = clf.predict(X_test)

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
print('confusion matrix = \n', confusion_matrix(y_true=y_test, y_pred=y_pred))
print('accuracy = ', accuracy_score(y_true=y_test, y_pred=y_pred))

confusion matrix = 
 [[ 23   5  18]
 [  4 132   3]
 [ 19   6 125]]
accuracy =  0.835820895522388


In [31]:
smodel_path = "../models/response2/"
smodel_name = "Classify_M_sbert.pickle"
smodelM = DataManager(smodel_path)

In [32]:
smodelM.save_data(smodel_name, clf)

success save : ../models/response2/Classify_M_sbert.pickle
